In [1]:
from Merge import *

ModuleNotFoundError: No module named 'pythoncom'

In [30]:
os.listdir(".\\Data\\Spreadsheets")

['Copy of Shelby Qtr. 4 2025 extra gift reports.xlsx',
 'Cover Sheet Q4-2025.docx',
 'DS - Cover Sheet Data (3).xlsx']

In [31]:
extraGiftFile = ".\\Data\\Spreadsheets\\Copy of Shelby Qtr. 4 2025 extra gift reports.xlsx"
tempsheet1 = pd.read_excel(extraGiftFile,sheet_name="Spons Xtra")
tempsheet1 = tempsheet1.rename(columns={
    "Actual Name": "eName",
    "Gross Amt": "Amo",
    "Prchr ID": "pNum",
    "Preacher Name": "pName",
    "Explanation": "eNum"
})[["eNum","eName","Amo","pNum"]].dropna()
tempsheet1["eNum"] = tempsheet1["eNum"].astype(int)
tempsheet1["pNum"] = tempsheet1["pNum"].astype(int)

tempsheet2 = pd.read_excel(extraGiftFile,sheet_name="DGR")
tempsheet2 = tempsheet2.rename(columns={
    "Actual Name": "eName",
    "Amt to Send": "Amo",
    "FUNDS_NAME": "pNum",
    "First 2": "eNum"
})[["eNum","eName","Amo","pNum"]].dropna()
tempsheet2["eNum"] = tempsheet2["eNum"].astype(int)
tempsheet2["pNum"] = tempsheet2["pNum"].astype(int)


giftDF = pd.concat([tempsheet1,tempsheet2],ignore_index=True)
giftDF.columns =["eNum","eName","Amo","pNum"]
giftDF = giftDF.astype(str)

In [32]:
tempsheet1

       eNum                           eName    Amo    pNum
5      4580                    Deena Finney  250.0  116006
6      3153             Christopher Tinsley    9.0  116038
7      6865              Raymond Washington   60.0  116025
8    604711  Titus Fellowship of Sioux City  575.0  116008
9      7421               Nate & Shari Voss  100.0  116021
..      ...                             ...    ...     ...
458    1787             Valerie Brotherhood  150.0  208059
459    1787             Valerie Brotherhood  150.0  208059
461    4756             Jim and Karen Baker  300.0  149711
462    4775           Keith and Rondy Bosch   45.0  149728
464    5970   Michael and Michelle Kingsley  500.0  127602

[421 rows x 4 columns]

In [33]:
giftDF

       eNum                           eName     Amo    pNum
0      4580                    Deena Finney   250.0  116006
1      3153             Christopher Tinsley     9.0  116038
2      6865              Raymond Washington    60.0  116025
3    604711  Titus Fellowship of Sioux City   575.0  116008
4      7421               Nate & Shari Voss   100.0  116021
..      ...                             ...     ...     ...
443    4470           Stephen and Anna Ross  4500.0  411069
444    7626            David & Natalie Hart    90.0  411050
445    7626            David & Natalie Hart    90.0  411054
446    3864          Joe and Sally Magalsky   120.0  411403
447    3864          Joe and Sally Magalsky    81.0  411403

[448 rows x 4 columns]

In [34]:
donordf = ".\\Data\\Spreadsheets\\DS - Cover Sheet Data (3).xlsx"
donors = getDonors(donordf)

In [35]:
findDonor(eNum="6397",donors=donors)

In [36]:
"6397" in donors.keys()

False